package org.avni_integration_service.goonj.domain;

public interface ActivityConstants {
    String RESOURCE_ACTIVITY = "ActivityService/upsertActivity";
    String LOCATION = "location";
    String STATE = "State";
    String DISTRICT = "District";
    String BLOCK = "Block";
    String OTHER_BLOCK = "Other Block";
    String VILLAGE = "Village";
    String OTHER_VILLAGE = "Other Village";
    String TOLA_MOHALLA = "Tola / Mohalla";
    String ACCOUNT_NAME = "Account  name";
    String TYPE_OF_INITIATIVE = "Type of initiative";
    String ACTIVITY_START_DATE = "Activity Start Date";
    String ACTIVITY_END_DATE = "Activity End Date";
    String ACTIVITY_TYPE = "Activity Type";
    String ACTIVITY_SUB_TYPE = "Activity sub type";
    String SPECIFY_OTHER_SUB_TYPE = "Specify Other Sub Type";
    String ACTIVITY_CATEGORY = "Activity category";
    String NUMBER_OF_WORKING_DAYS = "No of working days";
    String NUMBER_OF_PARTICIPANTS_MALE = "Number of Participants (Male)";
    String NUMBER_OF_PARTICIPANTS_FEMALE = "Number of Participants (Female)";
    String NUMBER_OF_PARTICIPANTS_OTHER = "Number of Participants (Other)";
    String NUMBER_OF_PARTICIPANTS = "Number of Participants";
    String NUMBER_OF_DAYS_OF_PARTICIPATION = "Number of Days of Participation";
    String ACTIVITY_CONDUCTED_WITH_STUDENTS = "Activity Conducted With Students";
    String TYPE_OF_SCHOOL = "Type of Educational Institute";
    String PHOTOGRAPH = "Photograph";
    String OBJECTIVE_OF_WORK = "Objective of Work";
    String SPECIFY_OTHER_FOR_OBJECTIVE_OF_WORK = "Any other not given above, Specify other";
    String SCHOOL_AANGANWADI_LEARNINGCENTER_NAME = "School / Anganwadi / Learning Center Name";
    String MEASUREMENTS_TYPE = "Measurements Type";
    String NOS = "Nos";
    String LENGTH = "Length";
    String BREADTH = "Breadth";
    String HEIGHT_DEPTH = "Height / Depth";
    String DIAMETER = "Diameter";
    String BEFORE_IMPLEMENTATION_PHOTOGRAPH = "Before implementation";
    String DURING_IMPLEMENTATION_PHOTOGRAPH = "During Implementation";
    String AFTER_IMPLEMENTATION_PHOTOGRAPH = "After implementation";
    String WORK_OBJECTIVE = "Work Objective";
    String WAS_DISCLAIMER_FORM_FILLED = "Was Undertaking Form Filled?";
    String FORM_CROSS_CHECKED ="Form Cross Checked?";
    String REMARKS ="Remarks";
    String OTHER_ACTIVITY = "Specify other activity";
}
