insert into integration_system (name, system_type, uuid) values ('lahi', 'lahi', uuid_generate_v4());

insert into error_type (name, integration_system_id, uuid) values ('CommonError', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), uuid_generate_v4());

INSERT INTO integrating_entity_status (id, entity_type, read_upto_numeric, read_upto_date_time, integration_system_id, uuid)
VALUES (DEFAULT, 'Student', 0, '2000-11-01', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), uuid_generate_v4());

insert into mapping_type (name, integration_system_id, uuid) VALUES ('Observations', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), uuid_generate_v4());

insert into mapping_group (name, integration_system_id, uuid) VALUES ('Student', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), uuid_generate_v4());

INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_father_name', 'Father''s name', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(),
        false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_other_qualification', 'Other qualifications', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_alternate_contact', 'Alternate (Whatsapp number)', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_email', 'Email address', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_highest_qualification', 'Highest qualification', 'Coded', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Upto 9th', 'Upto 9th', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '10th - SSC', '10th - SSC', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '11th - HSC', '11th - HSC', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '12th - HSC', '12th - HSC', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'ITI', 'ITI', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Diploma', 'Diploma', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Any other certification', 'Any other certification', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Other', 'Other', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Graduation', 'Graduation', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Post Graduation', 'Post Graduation', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(),
        false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_academic_year', 'Academic year for the qualification', 'Coded', (select id from integration_system where name = 'lahi' and system_type = 'lahi'),
        (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '2017-18', '2017-18', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '2018-19', '2018-19', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '2019-20', '2019-20', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '2020-21', '2020-21', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '2021-22', '2021-22', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '2022-23', '2022-23', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, '2023-24', '2023-24', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_qualification_status', 'Qualification status', 'Coded', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Appearing', 'Appearing', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Failed', 'Failed', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Pass out', 'Pass out', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Result Awaited', 'Results awaited', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(),
        false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_stream', 'Qualification stream', 'Coded', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Arts & Humanities', 'Arts & Humanities', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Commerce', 'Commerce', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Science-PCM', 'Science-PCM', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Science-PCB', 'Science-PCB', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Science-PCMB', 'Science-PCMB', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_vocational', 'Vocational or non vocational student?', 'Coded', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Vocational', 'Vocational', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Non-vocational', 'Non-vocational', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(),
        false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_trade', 'Trade/Sector', 'Coded', (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(),
        false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Agriculture', 'Agriculture', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Apparels , Made ups & Home Furnishing', 'Apparels , Made ups & Home Furnishing', null,
        (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Automotive', 'Automotive', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Beauty & Wellness', 'Beauty & Wellness', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Banking, Financial Services & Insurance', 'Banking, Financial Services & Insurance', null,
        (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Construction', 'Construction', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Electronics & Hardware', 'Electronics & Hardware', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Food Processing', 'Food Processing', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Handicrafts', 'Handicrafts', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Healthcare', 'Healthcare', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'IT/ITeS', 'IT/ITeS', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Media & Entertainment', 'Media & Entertainment', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Multiskilling', 'Multiskilling', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(),
        false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Physical Education and Sports', 'Physical Education and Sports', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'),
        (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Plumbing', 'Plumbing', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Power', 'Power', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Private Security', 'Private Security', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(),
        false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Retail', 'Retail', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Telecom', 'Telecom', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Tourism & Hospitality', 'Tourism & Hospitality', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'Transportation Logistics and Warehouse', 'Transportation Logistics and Warehouse', null,
        (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'avni_other_qualification_stream', 'Other qualification stream', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'),
        (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
INSERT INTO public.mapping_metadata (id, int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES (DEFAULT, 'contact_phone', 'Student contact number', null, (select id from integration_system where name = 'lahi' and system_type = 'lahi'), (select id from mapping_group where name = 'Student' and mapping_group.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), (select id from mapping_type where name = 'Observations' and mapping_type.integration_system_id = (select id from integration_system where name = 'lahi' and system_type = 'lahi')), uuid_generate_v4(), false);
