-- Init error_type
INSERT INTO error_type (name, integration_system_id, comparison_operator, comparison_value)
VALUES ('EntityIsDeleted', 2, NULL, NULL),
       ('NoDemandWithId', 2, NULL, NULL),
       ('NoDispatchWithId', 2, NULL, NULL),
       ('DemandIdChanged', 2, NULL, NULL),
       ('DispatchIdChanged', 2, NULL, NULL),
       ('NoSubjectWithId', 2, NULL, NULL),
       ('SubjectIdChanged', 2, NULL, NULL),
       ('MultipleSubjectsWithId', 2, NULL, NULL),
       ('SubjectIdNull', 2, NULL, NULL),
       ('ErroredAvniEncounter', 2, NULL, NULL),
       ('DemandAttributesMismatch', 2, NULL, NULL),
       ('DispatchAttributesMismatch', 2, NULL, NULL),
       ('DispatchReceiptAttributesMismatch', 2, NULL, NULL),
       ('DistributionAttributesMismatch', 2, NULL, NULL),
       ('ActivityAttributesMismatch', 2, NULL, NULL),
       ('DemandDeletionFailure', 2, NULL, NULL),
       ('DispatchDeletionFailure', 2, NULL, NULL),
       ('DispatchLineItemsDeletionFailure', 2, NULL, NULL),
       ('NoDemandWithId', 2, '2', 'Individual not found with UUID ''null'' or External ID ''.*'''),
       ('BadValueForRestrictedPicklist', 2, '1', 'INVALID_OR_NULL_FOR_RESTRICTED_PICKLIST'),
       ('MustNotHave2SimilarElements', 2, '1',
        'System.ListException: Before Insert or Upsert list must not have two identically equal elements'),
       ('FieldCustomValidationException', 2, '1', 'FIELD_CUSTOM_VALIDATION_EXCEPTION'),
       ('AnswerMappingIsNull', 2, '1',
        'Cannot invoke "org.avni_integration_service.integration_data.domain.MappingMetaData.getAvniValue()" because "answerMapping" is null'),
       ('TargetCommunityIsNullError', 2, '1',
        'Cannot invoke "String.split(String)" because the return value of "org.avni_integration_service.util.MapUtil.getString(String'),
       ('HttpClientErrorException', 2, '2', '400 : \"Answer concept with name=High Value Material not found\"'),
       ('NoImplementationInventoryWithId', 2, '2', 'Individual not found with UUID ''null'' or External ID ''.*'''),
       ('ImplementationInventoryIdChanged', 2, NULL, NULL),
       ('ImplementationInventoryAttributesMismatch', 2, NULL, NULL),
       ('HttpClientErrorException', 2, '2', '400 : \"Answer concept with name=test not found\"'),
       ('UnclassifiedError', 2, '1', '.*'),
       ('UpdateDispatchReceiptError', 2, '1', 'you cannot update dispatch receipt Status'),
       ('HttpClientErrorException', 2, '2', '400 : \"Answer concept with name=DFW not found\"'),
       ('ClassCastException', 2, '2', 'class java.lang.Integer cannot be cast to class java.lang.String'),
       ('DeleteEntityError', 2, '2', 'Failed to delete non-existent .*'),
       ('AddressNotFoundError', 2, '2', '500 : \"Address ''.*'' not found\"'),
       ('HttpClientErrorException', 2, '2', '400 Bad Request: .*');

-- Init integrating_entity_status
INSERT INTO integrating_entity_status
VALUES (DEFAULT, 'Inventory', NULL, '2021-01-01 00:00:00', 2),
       (DEFAULT, 'Demand', NULL, '2021-01-01 00:00:00', 2),
       (DEFAULT, 'Dispatch receipt', NULL, '2021-01-01 00:00:00.000', 2),
       (DEFAULT, 'Activity', NULL, '2021-01-01 00:00:00.000', 2),
       (DEFAULT, 'Distribution', NULL, '2021-01-01 00:00:00.000', 2),
       (DEFAULT, 'Dispatch', NULL, '2021-01-01 00:00:00', 2);



-- Init mapping_group
INSERT INTO mapping_group
VALUES (DEFAULT, 'Demand', 2),
       (DEFAULT, 'Dispatch', 2),
       (DEFAULT, 'DispatchLineItem', 2),
       (DEFAULT, 'Activity', 2),
       (DEFAULT, 'Dispatch receipt', 2),
       (DEFAULT, 'Distribution', 2),
       (DEFAULT, 'Inventory Item', 2);

-- Init mapping_type
INSERT INTO mapping_type
VALUES (DEFAULT, 'Observations', 2);

INSERT INTO public.mapping_metadata
VALUES (DEFAULT, 'NumberOfPeople', 'Number of people', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (SELECT id FROM mapping_group WHERE name = 'Demand'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'AccountId', 'AccountId', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (SELECT id FROM mapping_group WHERE name = 'Demand'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DemandId', 'DemandId', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (SELECT id FROM mapping_group WHERE name = 'Demand'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'TargetCommunity', 'Target Community', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (SELECT id FROM mapping_group WHERE name = 'Demand'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'TypeOfDisaster', 'Type of Disaster', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (SELECT id FROM mapping_group WHERE name = 'Demand'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'TypeOfMaterial', 'Type Of Material', NULL, 'Coded',
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Type', 'Kit Type', NULL, 'Coded', (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Quantity', 'Quantity', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'PurchaseItemCategory', 'Purchase Item Category', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'OtherKitDetails', 'Other Kit Details', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'KitName', 'Kit Name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'ItemCategory', 'Item Category', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Unit', 'Unit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchLineItemId', 'Dispatch Line Item Id', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Contributed', 'Contributed item', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Kit', 'Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Purchased', 'Purchased item', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Parlor', 'Parlor', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'S2S (GBG)', 'S2S (GBG)', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'S2S (Non-GBG)', 'S2S (Non-GBG)', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'S2S – AW', 'S2S – AW', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Office', 'Office', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Volunteer', 'Volunteer', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Vaapsi', 'Vaapsi', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Toiletry', 'Toiletry', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Other', 'Other', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'A', 'A', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'B', 'B', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'C', 'C', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Barber Kit', 'Barber Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Cobbler Kit', 'Cobbler Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Puncture Repair Kit', 'Puncture Repair Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Electrician Kit', 'Electrician Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Carpenter Kit', 'Carpenter Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Mason Kit', 'Mason Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Ironing Kit', 'Ironing Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Plumbing Kit', 'Plumbing Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Painter Kit', 'Painter Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Farmer Kit', 'Farmer Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Egg Shop Kit', 'Egg Shop Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Tea Shop Kit', 'Tea Shop Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Kirana Shop Kit', 'Kirana Shop Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Labor Kit', 'Labor Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Marriage Kits (M)', 'Marriage Kits (M)', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Marriage Kits (F)', 'Marriage Kits (F)', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchStatusName', 'Dispatch Status Name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchStatusId', 'Dispatch Status Id', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'KitId', 'Kit Id', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'MaterialId', 'Material Id', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Access_Infrastructure', 'Access Infrastructure', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Water_Management', 'Water Management', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Sanitation', 'Sanitation', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Agriculture_Plantation', 'Agriculture Plantation', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Miscellaneous', 'Miscellaneous Activity', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'ContributedItem', 'Contributed Item', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Contributed_Track', 'Contributed track', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch receipt'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Goonj Product', 'Goonj product', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Goonj Product', 'Goonj product', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch receipt'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'MaterialName', 'Material Name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Kit', 'Kit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch receipt'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Contributed', 'Contributed item', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch receipt'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Purchased', 'Purchased item', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch receipt'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Tent House', 'Tent house', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Marriage Kits', 'Marriage kits', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'New Born Baby', 'New born baby', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'My Pad Woman', 'My pad woman', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Dance Drama', 'Dance drama', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'KitSubType', 'Sub type', NULL, 'Coded',
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Contributed_Track', 'Contributed track', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Bulk Material', 'Bulk Material', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch receipt'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'CFW', 'CFW', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Bulk Material', 'Bulk Material', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'High Value Material', 'High Value Material', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'High Value Material', 'High Value Material', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch receipt'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'AccountName', 'Account  name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (SELECT id FROM mapping_group WHERE name = 'Demand'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'AccountCode', 'Account code', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'TypeofInitiative', 'Type of Initiative', NULL, 'Coded',
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'ActivityStartDate', 'Activity Start Date', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'ActivityEndDate', 'Activity End Date', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'ActivityType', 'Activity Type', NULL, 'Coded',
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'ActivitySubbType', 'Activity sub type', NULL, 'Coded',
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'OtherSubType', 'Specify Other Sub Type', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'ActivityCategory', 'Activity category', NULL, 'Coded',
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'NoofWorkingDays', 'No of working days', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Activity'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'CurrentQuantity', 'Current Quantity', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'BillName', 'Bill name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'OtherMaterialName', 'Other material name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'MaterialType', 'Material type', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'PurchaseKitName', 'Purchase Kit name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'PurchasedCreatedReceived', 'Purchased/ Created/ Received', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'MaterialName', 'Material Name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'SubType', 'Sub type', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'OriginalQuantity', 'Initial Quantity', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'ImplementationMaterialSubCategory', 'Material sub category', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchReceivedStatusLineItem', 'Dispatch Received Status Line Item Id', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'VehicleType', 'Vehicle type', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'CenterFieldOffice', 'Center / Field office', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchLineItemID', 'Dispatch Line Item Id', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'KitType', 'Kit Type', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchID', 'Dispatch Status Id', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Purchased', 'Purchased item', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Contributed', 'Contributed item', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'SourceOfMaterial', 'Type Of Material', NULL, 'Coded',
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Unit', 'Unit', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DateOfReceiving', 'Dispatch Received Date', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchStatusName', 'Dispatch Status Name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'AccountName', 'Account  name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'X', 'X', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'DispatchLineItem'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DemandId', 'DemandId', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Demand', 'Demand name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'FromWhichAccount', 'Account  name', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Inventory Item'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DemandStatus', 'Demand Status', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (SELECT id FROM mapping_group WHERE name = 'Demand'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchStatus', 'Dispatch Status', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (SELECT id FROM mapping_group WHERE name = 'Demand'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'Status', 'Status', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch'),
        (select id from mapping_type where name = 'Observations')),
       (DEFAULT, 'DispatchStage', 'Dispatch Stage', NULL, NULL,
        (select id from integration_system where name = 'Goonj'),
        (select id from mapping_group where name = 'Dispatch'),
        (select id from mapping_type where name = 'Observations'));