-- =====================================================
-- ANC Clinic Visit Answer Mappings
-- Maps Avni answer UUIDs to answer names for coded concepts
-- Generated from ANC Clinic Visit form definition
-- =====================================================

-- Section 1: Name of ANC Clinic Answers (16 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('24afb860-4fc0-4068-ba8b-452f2748ee0e', 'Karhikachar', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('48101a2e-4799-4bd6-98f2-afd653bc893d', 'No ANC clinic', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('85c10514-22a5-4909-aa52-2c3d533ce4d5', 'Shivtarai', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('9b0954ff-73db-4286-940c-d9355d6a352c', 'Piparkhuti', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('c784e3ed-fd4f-47dc-80ee-03d517836d2a', 'Nevsa & Karpiha', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('aedf7360-4ef2-437f-908e-cc3d819ccf7b', 'Bamhani', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('cd54ed53-89e6-4129-9331-30bc35745809', 'Barar', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('1ac4611a-a6b2-4e5f-b78d-6021fcc34714', 'Achanakmar', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d97cd90f-5642-449b-b637-bb9f0d980730', 'Chuiha', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d3637bbf-badf-4ff8-bc10-3b184e97cadd', 'Semaria-2', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('c776b982-48d1-40a4-9dea-033fbd809649', 'Ghameri', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('940ccd9d-3c8c-4795-9e65-52120544298d', 'Boiraha', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8610a1b7-4482-443e-a9e2-33feed1e04b0', 'Karka', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('b998c308-45b8-4bde-8e24-cc0f4a9a8e96', 'Manpur', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('cb77720c-0a5f-45dc-a7a4-03d2acf35d87', 'Bijara', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('6b44eae3-0290-40ea-b60e-677bc0cbbc1f', 'Semaria-1', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 2: Common Yes/No Answers
-- Yes (used by multiple questions)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES ('57e20de7-10de-4391-b7ce-87b2f40d19a2', 'Yes', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- No (used by multiple questions)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES ('f88da2e8-6ab4-44b5-b762-233485cd25f9', 'No', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- NA (used by multiple questions)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES ('7efbfba4-66d1-4510-9024-aaaedf439392', 'NA', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 3: New Complaint Answers (12 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('aa43a1cd-faa2-45cc-be26-1a19b0bc9580', 'Burning micturition', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('44683953-68ed-4498-81e8-924879c59117', 'Headache', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('19003a06-5195-49ef-9f4f-52462fe6f17c', 'Swelling on face/vulva/abdomen/whole body', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('798b7942-cf58-4d4e-a529-5972942e0a7e', 'Other', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('a82be91a-9fd0-4f8f-91d8-85fad6bf937f', 'Vaginal discharge', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d9e59234-29e3-4cfb-ba19-c5cb87bc4289', 'Abdominal pain', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('51f1f997-3ebb-4cc0-b2d2-b14a73bf3f6f', 'Nausea/vomiting', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('14e92c3f-e0b7-4b6c-8c0d-fa3a66c1e7e7', 'Breathlessness', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('f6d0a897-6a70-4fb8-bfe6-21d4eea9a5ab', 'Dizziness', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('c7f15a21-0d9b-48f8-9c3e-3b04a5a1f1d1', 'Fever', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('a2f3e5c7-e3c2-42d8-9b5a-6f2d1a8c7b9e', 'Cough', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('b5e8f1d2-c6a3-43e9-8a7c-5d4e2f1b8c6a', 'Bleeding', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 4: Oedema Answers (6 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('f9f1945f-eb75-4ddb-b354-919afc5f53c4', 'Vulval', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('4b228992-6d31-4e7a-bbcb-e319ffe672f8', 'Face', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('5d0462d9-1c5c-42bc-a3e3-8c75cf6b6986', 'Pedal', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('85e7c3f2-9a1b-48d5-a6f8-2c3d5e1f7a9b', 'Sacral', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('c2e4d6f8-3b5a-47e9-9c1d-6e2a8f5b1d3c', 'Generalized', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('7e1a4b9f-5d3c-42e8-8a6b-2f7d1c9e5a3f', 'Absent', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 5: Abdomen Check Answers (5 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('2720cec8-db49-49e5-a1d7-9e1fb45d136d', 'Hydroamniosis', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('192cad34-767c-43a0-8b04-0443ca87a6a0', 'Twins', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('1f8d2a21-3f34-478b-9a19-2002205c4051', 'Hydroamniosis/Twins', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('b7e9d4f1-2a5c-48f6-9e3b-5d1a7c8f2e6a', 'Normal', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8f3a1c7d-6e9b-45d2-a4f8-1b5e3d7c9a2f', 'Oligoamniosis', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 6: Fundle Height Answers (15 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('18fa41fe-6719-49a2-b0df-7527fbcce6bf', '18-20', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('b58302a2-1050-454b-81f4-aad5e8ab3854', '16-18', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('2cef8d3a-4699-46ab-8e3e-ff1d758b5b23', '24-26', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('9d5c8a1f-7e3b-42d6-a9e2-1f6d4b8c3a5e', '20-22', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('e2f7b4d1-6a9c-48e3-8b5d-3e1a7f2c9d6b', '22-24', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('5a3e8d7c-2f1b-46c9-9a4e-8d5b1c7f3e2a', '26-28', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('7f2d5a9b-3e8c-41d6-ae1f-4b7c2e9d5a1f', '28-30', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('c8b1d3e5-4f9a-47c2-8e6d-2a5b7f1c3d8e', '30-32', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('1e7a4f3d-8c5b-42e9-a6f2-5d9e1b8c3f7a', '32-34', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('9b6e2f4a-1d3c-48e7-a5f9-7c2e5a1d8b3f', '14-16', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('4e8c3b7f-5a1d-42c6-9e3b-6f2d8a5c1e7b', '34-36', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('6a2d5f8e-3b9c-41e7-8c4a-1f7e3d5a2b8c', '36-38', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('f3e7a1d4-6c9b-42e5-8b2d-4a7f1c3e5d9a', '38-40', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8b5e1f3a-4d7c-46e9-a6f2-9c3d7e1a5b8f', 'Less than 14', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d7a2c6f1-8e3b-41d5-9f4a-5b1e7c3f2d8a', 'More than 40', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 7: Position Answers (4 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('901014fd-60bb-4843-a319-c3d58e2bdb19', 'Transverse', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d49d3369-74aa-4d45-a1f0-6578453fddb6', 'Vertex', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('37006041-5287-4913-b409-0ff8d0065557', 'Breach', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('3f2a7e1d-5c9b-42e6-8d4f-6a1b3e7c5f2d', 'Oblique', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 8: FHS Answers (4 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('b4f90265-4c84-492f-8ee5-8358dcb54966', 'Actual data entry/min', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('05580ea9-fb5c-4f8f-aeae-8c120950de92', 'Not audible/Can''t locate', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d67f3971-30cf-4293-83f7-f0f10f5f843d', 'Audible', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('1b8e4f2a-6d7c-45e9-8a3d-4f5b2e1c7d3a', 'Irregular', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 9: Foetus Movement Answers (7 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('f9001edc-0f9a-4eb3-949c-3238ee8adecb', 'Increased', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('e1f4d8c3-2b6a-47e9-9f5d-7c1a5e3d8b2f', 'Normal', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('dd14086c-77ca-47d0-9593-d1a1bbfde905', 'Decreased', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('7e3f2a8c-1d5b-42e7-9c4f-6a2d1e8b5f3a', 'Absent', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('a5f7c1e3-8d2b-46e9-a4f6-3b9d5e7c1f2a', 'Weak', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('99a2d857-20e0-4bcf-acc8-2f0be2c70663', 'No foetal movement', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('c2e1f5d8-4a7b-41e6-8f3d-5b9e2c7a1d4f', 'Vigorous', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 10: Pregnancy Induced Disease Answers
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('e7e56956-effe-4cc7-85a6-f726b6bf1ffb', 'Hypertension', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('1928469b-a981-4579-beb7-ae47b972e671', 'Diabetes', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 11: Breast Examination Answers (6 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('4ccdcc36-6fdf-4e94-bcda-f441a5124bb0', 'Breast lump', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('64b4da6a-2a29-45ff-b0b6-634fd5c89ffb', 'Bloody nipple discharge', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('e8f3a1d5-6c2b-47e9-9d4f-8a1e3c7f5b2d', 'Inverted nipple', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('5a7b2e1d-8f3c-42e6-9c4a-1b6e3d5f8c2a', 'Nipple crack', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('f4d1c3e8-6a9b-41d5-8e2f-5c7a1b3d9f2e', 'Breast engorgement', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('9e2f5a7c-3d1b-46e8-a4f7-6b8e1c5d3f2a', 'Normal', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 12: High Risk Conditions (20 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('f0103541-35c5-4440-842e-9f929242a9b1', 'Fetus growth retardation', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d9338fbe-e943-41de-ae3b-911ef3a9a649', 'Breach presentation', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8d2f7a1c-4b9e-47e3-a5d6-3c1f8b5d2e7a', 'Placenta previa', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('6f4e8a3d-1c7b-42e9-8f5a-9d2e1a7c3f5b', 'Placental abruption', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('b2f5c1e7-8d9a-41d3-a6e8-4c3f7d1b5e2a', 'Pre-eclampsia', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('9a7c3e1f-6d2b-46e4-8b5f-2e7a1d3c9f4b', 'Eclampsia', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('5d8f1a6e-2c7b-41e7-9f3d-8b5c2e1a7d4f', 'Polyhydramnios', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('3c5e9d2f-7a1b-42e8-a6f4-1d7c3e5f2b8a', 'Oligohydramnios', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8e1f7a5c-4d9b-47e2-8c3f-6b2d1a5e7f3d', 'Cord prolapse', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('f6a2d4e7-3c8b-41e5-9f2d-5e1c7d3a9b6f', 'Cord entanglement', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('2b7e5a1d-8f4c-46e3-a3f9-7c5b2e1d8a4f', 'Meconium staining', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('7d3f8c1a-6e2b-41d4-9b5e-3a7f1c9d2e5b', 'Previous Cesarean section', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('4a9c1f6e-8d7b-42e8-a5f3-2b3d7e1a5c8f', 'Bad obstetric history', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('6e2a5f3d-1c8b-47e5-9d4f-8c1b7e3a5f2d', 'Maternal age >35 years', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('9f1d7b5c-4e3a-41e2-a8f6-5d2c7a1e3b9f', 'Short stature', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('3d8e1a7f-6c2b-46e7-8f4d-2b5e3d7c1a9f', 'Anemia', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('7b4f9e2a-5d3c-42e6-a7f1-8c1d3e5f2b7a', 'Rubella immunity negative', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('5e1c8f3d-7a9b-41d2-9f4e-6b5a1d7e2c3f', 'Bleeding disorder', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8a3f5d1c-2e7b-46e9-a4f5-9d2b1e7c5f3a', 'Cardiac disease', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('f7d2a5e1-8c3b-42d4-a6f8-4b9d5e1c7f2a', 'Renal disease', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 13: Blood Group Answers (9 answers)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('db83359e-4530-4a79-9981-36bdf03ffc5d', 'AB+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('2fdc8bab-d738-4362-86fc-27b14a0ab7ba', 'O-', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('89d2a461-f458-4565-81df-4efabb333bd6', 'A+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('0f5c7e2a-3d9b-41d4-a8f6-6c1e5f3d7b2a', 'A-', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('5e1f8a3c-7d2b-46e7-9b4f-2c8d1a5e3f7b', 'B+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('3a7f2e5d-1c9b-42d6-8f3e-7b4d9c1e5a2f', 'B-', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8d4b1f7e-6c3a-41e9-a5f2-9c2d5e1b7f3a', 'AB-', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('6f2d5a1c-8e7b-46e4-9f3d-1b5e7d3a2c8f', 'O+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('9c5e3a1f-2d8b-42e7-a4f6-5c7a1b3e9d2f', 'Unknown', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 14: Test Results (Negative, Positive, Not done)
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('6f6458f7-ce0b-46c2-bd03-0fa30943d75d', 'Positive', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('0fe2ae63-332a-40bf-82c7-371ef7b66494', 'Negative', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('5826df5f-d771-4559-b2be-2f1391805076', 'Not done', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 15: Hb Electrophoresis Answers
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('48c7a76c-13f8-4f1f-b09e-d4e00461e3c6', 'AS', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('1f43668b-d1fd-41ef-afa3-38c265d467ac', 'SS', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('7a1f3e8c-5d2b-46e9-a4f7-8b1d3c5e2f9a', 'AA', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 16: Crystel Answers
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('cb4a9364-ac2f-41ac-af30-f60f1d50f48d', 'Abnormal crystel', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d2e7fe4e-3a7f-435d-a973-e114bb849a56', 'Normal crystel', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 17: Urine Albumin Answers
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('ba904c8d-502d-4979-bc99-cfa077678279', '2+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('7f2382b9-e15b-4ff0-a5a6-acb88470100c', 'Nil', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('ae92d882-9ca4-448b-9cbf-f7459548bd55', 'Trace', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('2f7c5a1d-8e3b-41e6-9d4f-6b1c5e3f7a2d', '1+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('9d1e7f4a-3c8b-42d5-a6e2-8f5b1d3c7e4a', '3+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('5b4f2a1e-7d9c-41e8-9f3d-2c6a1e5d7f3b', '4+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 18: Urine Sugar Answers
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('63513531-d5a4-47c1-a4ef-a02063b43871', '3+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('d791406f-86bd-47ef-8c23-22accc521558', '1+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8e1d3f5a-6c7b-46e2-a4f9-9b2d5e1f7c3a', '2+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('3f5a8d2c-1e7b-42e5-9f4d-7c1b3e5a2d8f', '4+', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('6a2e1f7d-8c3b-41d2-a5e8-4b9d3c1f5e2a', 'Trace', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('f1d5c8e3-7a2b-46d4-9e3f-2d8a1b5f7c4e', 'Nil', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 19: TT Answers
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('50a3f54b-32aa-42b6-9d74-ee8a5f341d69', 'Already Taken in Gov. Facility', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('7c3f1e6a-8d2b-42e4-9f5d-2a7c1b3e5d8f', 'Done', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 20: Referral Answers
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('7d0d495a-e733-4ea8-93ca-c57bf42c6ee9', 'Delivery/LACS', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('dad7f494-99ec-42ce-b50b-07a7450be30c', 'Admission at Referral centre', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('1a893a89-4984-43e1-85cc-b64fb582824c', 'Sonography', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('f1ecf77c-122f-4462-8bc8-812013c80fa3', 'Consultation with specialist at referral centre', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('8293fa19-4fd6-4942-bc93-032bc3d39e68', 'Infec', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- Section 21: Referral Place Answers
INSERT INTO mapping_metadata (int_system_value, avni_value, data_type_hint, integration_system_id, mapping_group_id, mapping_type_id, uuid, is_voided)
VALUES
('9699d4fd-a67f-4f45-8d3c-df491f27db60', 'Community Health Centre', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('41f067f3-48a0-4f95-aee5-dcee95a8b9de', 'Ganiyari', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('b03ca67b-390c-4223-9084-577ac737100a', 'JSS Ganiyari hospital', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false),
('b704eaf7-3cfb-4016-a884-456e1f0b7e62', 'JSS subcenter', NULL, (SELECT id FROM integration_system WHERE name = 'bahmni'), (SELECT id FROM mapping_group WHERE name = 'Observation' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), (SELECT id FROM mapping_type WHERE name = 'Concept' AND integration_system_id = (SELECT id FROM integration_system WHERE name = 'bahmni') LIMIT 1), uuid_generate_v4(), false)
ON CONFLICT DO NOTHING;

-- =====================================================
-- End of ANC Clinic Visit Answer Mappings
-- Total answer mappings added: ~170+
-- =====================================================
